name: BabelPlugin
author: oSLiD3Ro,ThunderGemios10
version: 0.9.2

main: me.bukkit.babelplugin.BabelPlugin

commands:
  startgame:
    description: Starts the Game
    usage: </startgame>
  endgame:
    description: Ends the Game
    usage: </endgame>
