name: BabelPlugin
author: oSLiD3Ro, ThunderGemios10
version: 0.9.2-B

main: me.thundergemios10.babelplugin.BabelPlugin

commands:
  startgame:
    description: Starts the Game
    usage: </startgame>
  endgame:
    description: Ends the Game
    usage: </endgame>
